jaffle_shop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /usr/src/app/.secrets/dbt-user-creds.json
      project: foo-bar-1800
      dataset: dbt
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive